name: danse_env
channels:
  - defaults
dependencies:
  - python=3.7
  - pytorch=1.6.0
  - matplotlib=3.4.3
  - scipy=1.7.3
  - sklearn=1.0.1
  - filterpy=1.4.5
  - jupyter>= 6.4.6
  - pip:
    - tikzplotlib
